#!/usr/bin/env bash

set -ex

case "${DOCKER_TAG}" in
*-dev-test)
    docker_target=developer-build
    target=${DOCKER_TAG%"-dev-test"}
    ;;
*-test)
    docker_target=build
    target=${DOCKER_TAG%"-test"}
    ;;
*)
    exit 1
    ;;
esac

pushd ..
. env/$target.env
build_args=$(./env/env2arg.py env/$target.env)
popd

docker build \
    -f ${DOCKERFILE_PATH} \
    -t ${IMAGE_NAME} \
    ${build_args} \
    --target $docker_target \
    .
